-- Lua bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/DetailController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:11 +0000



-- Objective C interface: @interface DetailController
local DetailController = objc.classInterface ("DetailController") --[[ @inherits WKInterfaceController]]

DetailController.nameLabel --[[@type objc.WKInterfaceLabel]] = nil
DetailController.image --[[@type objc.WKInterfaceImage]] = nil
DetailController.descriptionLabel --[[@type objc.WKInterfaceLabel]] = nil
function DetailController:nameLabel ()  --[[@return objc.WKInterfaceLabel]] end
function DetailController:setNameLabel (nameLabel --[[@type objc.WKInterfaceLabel]])  --[[@return nil]] end
function DetailController:image ()  --[[@return objc.WKInterfaceImage]] end
function DetailController:setImage (image --[[@type objc.WKInterfaceImage]])  --[[@return nil]] end
function DetailController:descriptionLabel ()  --[[@return objc.WKInterfaceLabel]] end
function DetailController:setDescriptionLabel (descriptionLabel --[[@type objc.WKInterfaceLabel]])  --[[@return nil]] end