-- Lua bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/InterfaceController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:10 +0000



-- Objective C interface: @interface InterfaceController
local InterfaceController = objc.classInterface ("InterfaceController") --[[ @inherits WKInterfaceController]]

InterfaceController.label --[[@type objc.WKInterfaceLabel]] = nil
InterfaceController.nextButton --[[@type objc.WKInterfaceButton]] = nil
InterfaceController.previousButton --[[@type objc.WKInterfaceButton]] = nil
InterfaceController.imageGroup --[[@type objc.WKInterfaceGroup]] = nil
function InterfaceController:showNext ()  --[[@return nil]] end
function InterfaceController:showPrevious ()  --[[@return nil]] end
function InterfaceController:label ()  --[[@return objc.WKInterfaceLabel]] end
function InterfaceController:setLabel (label --[[@type objc.WKInterfaceLabel]])  --[[@return nil]] end
function InterfaceController:nextButton ()  --[[@return objc.WKInterfaceButton]] end
function InterfaceController:setNextButton (nextButton --[[@type objc.WKInterfaceButton]])  --[[@return nil]] end
function InterfaceController:previousButton ()  --[[@return objc.WKInterfaceButton]] end
function InterfaceController:setPreviousButton (previousButton --[[@type objc.WKInterfaceButton]])  --[[@return nil]] end
function InterfaceController:imageGroup ()  --[[@return objc.WKInterfaceGroup]] end
function InterfaceController:setImageGroup (imageGroup --[[@type objc.WKInterfaceGroup]])  --[[@return nil]] end