-- Lua bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/MapController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:11 +0000



-- Objective C interface: @interface MapController
local MapController = objc.classInterface ("MapController") --[[ @inherits WKInterfaceController]]
