-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/WatchApp1/WatchApp1 WatchKit Extension/MapController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-16 12:39:21 +0000



-- Objective C interface: @interface MapController
local MapController = objc.classInterface ("MapController") --[[ @inherits WKInterfaceController]]
