-- Lua bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/NotificationController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:11 +0000



-- Objective C interface: @interface NotificationController
local NotificationController = objc.classInterface ("NotificationController") --[[ @inherits WKUserNotificationInterfaceController]]
