-- Lua bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/SpearmanController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:10 +0000



-- Objective C interface: @interface SpearmanController
local SpearmanController = objc.classInterface ("SpearmanController") --[[ @inherits WKInterfaceController]]
