// Lua to C bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/DetailController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:11 +0000
// Target Architecture: arm64

#import "CIMLua/CIMLuaBindings.h"

#import "DetailController.h"

// Register Objective C methods extended signatures

@implementation DetailController (LuaModule_WatchApp1WatchKitExtension_DetailController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(nameLabel), "@\"WKInterfaceLabel\"16@0:8" },
        { @selector(setNameLabel:), "v24@0:8@\"WKInterfaceLabel\"16" },
        { @selector(image), "@\"WKInterfaceImage\"16@0:8" },
        { @selector(setImage:), "v24@0:8@\"WKInterfaceImage\"16" },
        { @selector(descriptionLabel), "@\"WKInterfaceLabel\"16@0:8" },
        { @selector(setDescriptionLabel:), "v24@0:8@\"WKInterfaceLabel\"16" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:6 forClass:[DetailController class]];
}

@end

