// Lua to C bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/DetailController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:11 +0000
// Target Architecture: armv7

#import "CIMLua/CIMLuaBindings.h"

#import "DetailController.h"

// Register Objective C methods extended signatures

@implementation DetailController (LuaModule_WatchApp1WatchKitExtension_DetailController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(nameLabel), "@\"WKInterfaceLabel\"8@0:4" },
        { @selector(setNameLabel:), "v12@0:4@\"WKInterfaceLabel\"8" },
        { @selector(image), "@\"WKInterfaceImage\"8@0:4" },
        { @selector(setImage:), "v12@0:4@\"WKInterfaceImage\"8" },
        { @selector(descriptionLabel), "@\"WKInterfaceLabel\"8@0:4" },
        { @selector(setDescriptionLabel:), "v12@0:4@\"WKInterfaceLabel\"8" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:6 forClass:[DetailController class]];
}

@end

