// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/WatchApp1/WatchApp1 WatchKit Extension/DetailController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-09-16 12:39:20 +0000
// Target Architecture: arm64

#import "CIMLua/CIMLuaBindings.h"

#import "DetailController.h"

// Register Objective C methods extended signatures

@implementation DetailController (LuaModule_WatchApp1WatchKitExtension_DetailController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(nameLabel), "z@\"WKInterfaceLabel\"16@0:8" },
        { @selector(setNameLabel:), "v24@0:8z@\"WKInterfaceLabel\"16" },
        { @selector(image), "z@\"WKInterfaceImage\"16@0:8" },
        { @selector(setImage:), "v24@0:8z@\"WKInterfaceImage\"16" },
        { @selector(descriptionLabel), "z@\"WKInterfaceLabel\"16@0:8" },
        { @selector(setDescriptionLabel:), "v24@0:8z@\"WKInterfaceLabel\"16" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:6 forClass:[DetailController class]];
}

@end

