// Lua to C bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/InterfaceController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:10 +0000
// Target Architecture: arm64

#import "CIMLua/CIMLuaBindings.h"

#import "InterfaceController.h"

// Register Objective C methods extended signatures

@implementation InterfaceController (LuaModule_WatchApp1WatchKitExtension_InterfaceController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(label), "@\"WKInterfaceLabel\"16@0:8" },
        { @selector(setLabel:), "v24@0:8@\"WKInterfaceLabel\"16" },
        { @selector(nextButton), "@\"WKInterfaceButton\"16@0:8" },
        { @selector(setNextButton:), "v24@0:8@\"WKInterfaceButton\"16" },
        { @selector(previousButton), "@\"WKInterfaceButton\"16@0:8" },
        { @selector(setPreviousButton:), "v24@0:8@\"WKInterfaceButton\"16" },
        { @selector(imageGroup), "@\"WKInterfaceGroup\"16@0:8" },
        { @selector(setImageGroup:), "v24@0:8@\"WKInterfaceGroup\"16" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:8 forClass:[InterfaceController class]];
}

@end

