// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/WatchApp1/WatchApp1 WatchKit Extension/InterfaceController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-09-16 12:39:19 +0000
// Target Architecture: armv7

#import "CIMLua/CIMLuaBindings.h"

#import "InterfaceController.h"

// Register Objective C methods extended signatures

@implementation InterfaceController (LuaModule_WatchApp1WatchKitExtension_InterfaceController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(label), "z@\"WKInterfaceLabel\"8@0:4" },
        { @selector(setLabel:), "v12@0:4z@\"WKInterfaceLabel\"8" },
        { @selector(nextButton), "z@\"WKInterfaceButton\"8@0:4" },
        { @selector(setNextButton:), "v12@0:4z@\"WKInterfaceButton\"8" },
        { @selector(previousButton), "z@\"WKInterfaceButton\"8@0:4" },
        { @selector(setPreviousButton:), "v12@0:4z@\"WKInterfaceButton\"8" },
        { @selector(imageGroup), "z@\"WKInterfaceGroup\"8@0:4" },
        { @selector(setImageGroup:), "v12@0:4z@\"WKInterfaceGroup\"8" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:8 forClass:[InterfaceController class]];
}

@end

