// Lua to C bindings for /Users/jean-luc/Desktop/LuaWatchKitFirstApp/WatchApp1 WatchKit Extension/InterfaceController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-05-20 17:20:10 +0000
// Target Architecture: armv7

#import "CIMLua/CIMLuaBindings.h"

#import "InterfaceController.h"

// Register Objective C methods extended signatures

@implementation InterfaceController (LuaModule_WatchApp1WatchKitExtension_InterfaceController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(label), "@\"WKInterfaceLabel\"8@0:4" },
        { @selector(setLabel:), "v12@0:4@\"WKInterfaceLabel\"8" },
        { @selector(nextButton), "@\"WKInterfaceButton\"8@0:4" },
        { @selector(setNextButton:), "v12@0:4@\"WKInterfaceButton\"8" },
        { @selector(previousButton), "@\"WKInterfaceButton\"8@0:4" },
        { @selector(setPreviousButton:), "v12@0:4@\"WKInterfaceButton\"8" },
        { @selector(imageGroup), "@\"WKInterfaceGroup\"8@0:4" },
        { @selector(setImageGroup:), "v12@0:4@\"WKInterfaceGroup\"8" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:8 forClass:[InterfaceController class]];
}

@end

